name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-18.04

    # https://github.com/elixir-lang/elixir/blob/master/lib/elixir/pages/compatibility-and-deprecations.md
    strategy:
      matrix:
        include:

          # Elixir 1.9

          - elixir: 1.9.0
            otp_release: 21.3.8.24

          - elixir: 1.9.0
            otp_release: 22.3.4.23

          # Elixir 1.10

          - elixir: 1.10.0
            otp_release: 21.3.8.24

          - elixir: 1.10.0
            otp_release: 22.3.4.23

          - elixir: 1.10.3
            otp_release: 23.3.4.9

          # Elixir 1.11

          - elixir: 1.11.4
            otp_release: 21.3.8.24

          - elixir: 1.11.4
            otp_release: 22.3.4.23

          - elixir: 1.11.4
            otp_release: 23.3.4.9

          - elixir: 1.11.4
            otp_release: 24.1.6

          # Elixir 1.12

          - elixir: 1.12.3
            otp_release: 22.3.4.23

          - elixir: 1.12.3
            otp_release: 23.3.4.9

          - elixir: 1.12.3
            otp_release: 24.1.6

          # Elixir 1.13

          - elixir: 1.13.4
            otp_release: 22.3.4.23

          - elixir: 1.13.4
            otp_release: 23.3.4.9

          - elixir: 1.13.4
            otp_release: 24.2.1

          - elixir: 1.13.4
            otp_release: 25.1.1

          # Elixir 1.14

          - elixir: 1.14.1
            otp_release: 23.3.4.9

          - elixir: 1.14.1
            otp_release: 24.2.1

          - elixir: 1.14.1
            otp_release: 25.1.1

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp_release }}
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ matrix.elixir }}-${{ matrix.otp_release }}-${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test

  send_coveralls:
    name: Send coveralls stats
    runs-on: ubuntu-18.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MIX_ENV: test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.10.4' # Define the elixir version [required]
        otp-version: '23.0' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: coveralls-${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
    - name: Install dependencies
      run: mix deps.get
    - name: Send coveralls
      run: mix coveralls.github

